version: "3"
services:
  db:
    container_name: mysql_container
    image: mysql:5.7
    volumes:
      - ./cria_camadas.sql:/docker-entrypoint-initdb.d/cria_camadas.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_ARGS: --max_allowed_packet=64M

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: python_app
    links:
      - db
    ports:
      - "5001:5000"